version: "3"
services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: uzt_lt
      POSTGRES_PASSWORD: uzt_LT_01
